### ISSUE TITLE
Spike : Plan for server setup tasks

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/west-virginia-university#1]
# Summary

We will be using local servers to set up the WVU application in order to reduce costs.  April and Rob already have VPN access and ssh access to the servers.  This issue is to plan the activities that need to happen in order to deploy the application on the client servers.  

Notes on meeting including server questions: https://docs.google.com/document/d/1jQ9vDgpRGBaNZj5H7Rp7hbsEOEEfAq4d1_n0dcMGIdE/edit#heading=h.3zeglegwljh
Notes on general project: https://docs.google.com/document/d/1xeL62Zxkhp7Ftu8bnEq92WAdZZcIGjgurPI2H90KdEo/edit#heading=h.3zeglegwljh

# Acceptance Criteria

- [ ] Follow up tickets are for setup and deployment of the project have been created.  

# Notes

**Comment by aprilrieger** [comment]
look at the parts and pieces in the forked repository
what do they have on the server that Rob and I have access to.
-- we are hoping to have an answer to setting up a staging instance.
Do they have kubernetes
What do they use for deployment etc.

**Comment by aprilrieger** [comment]
WVU Server access instructions:


![Image](https://user-images.githubusercontent.com/63515648/220438927-c42d1737-203b-429a-bc77-a5ee2e8f7b6d.png)



![Image](https://user-images.githubusercontent.com/63515648/220438948-ad3b7929-098d-4cbb-81c8-3506ab13a0b9.png)

Once connected via VPN you will be able to connect to the serve via ssh by using this format:
`ssh ar00116@congressarchivesdev.lib.wvu.edu`

Replace my username `ar00116` with your username.

**Comment by aprilrieger** [comment]
`uname -a` Output:
```yaml
Linux congressarchives.lib.wvu.edu 4.18.0-372.32.1.el8_6.x86_64 #1 SMP Fri Oct 7 12:35:10 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```
`cat /etc/*release*` Output:
```yaml
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"
Red Hat Enterprise Linux release 8.6 (Ootpa)
Red Hat Enterprise Linux release 8.6 (Ootpa)
cpe:/o:redhat:enterprise_linux:8::baseos
```

**Comment by aprilrieger** [comment]
The repo is cloned to: `/home/git_pulls/hydra_acda_portal_public` on the VM and we have git write access to the repo. Any pushing should be done to a new branch.

**Comment by aprilrieger** [comment]
<img width="1455" alt="Screenshot 2023-03-03 at 10 01 23" src="https://user-images.githubusercontent.com/63515648/222794880-1c618ab6-b1e2-4fcb-acf6-7282a56b879f.png">
<img width="603" alt="Screenshot 2023-03-03 at 10 02 03" src="https://user-images.githubusercontent.com/63515648/222794888-3f8cb717-135f-4f5f-b6cf-5eb89a26ba01.png">

**Comment by aprilrieger** [comment]
Documentation:
- https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/8.6_release_notes/index
-

**Comment by aprilrieger** [comment]
I dont have access to their ansible playbook, and do not have access to the ansible folder on the box located at `./home/ansible`, not sure if it is necessary but it sure would be nice to see so we can develop our own stratgey.

**Comment by aprilrieger** [comment]
![Image](https://user-images.githubusercontent.com/63515648/223221994-e4748e9a-c83d-4e4b-a6e2-ff6dc695d55a.png)

issue with fcrepo in prod

**Comment by aprilrieger** [comment]
Ask client for their deployment process

release based structure for ppl that are behind vpn, put chron that runs that checks the latest release and then the server triggers it's release automatically. Pool of code and then pull down the local changes, git pull, docker restart, run migrations and get back up and running again.

**Comment by aprilrieger** [comment]
Waiting for client feedback at client meeting this week

**Comment by crisr15** [comment]
- [ ] Would like auto deployment.  
- [ ] Also need instruction on configuring fedora instance.
