### ISSUE TITLE
As a user, I can further refine the advanced search functionality through the facets that are available on regular search

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/west-virginia-university#100]
## Summary
related to 
- #92 

## Accepted Criteria
- [ ] As a user, I can further refine the advanced search functionality through the facets that are available on regular search

## Testing Instruction
- [ ] Navigate to the `More options`
- [ ] Play around with the options and observe that they work as expected

**Comment by ShanaLMoore** [comment]
# QA Results: PASS ✅ 

- [X] As a user, I can further refine the advanced search functionality through the facets that are available on regular search


![Image](https://github.com/scientist-softserv/west-virginia-university/assets/19597776/d1a7fce6-8d1f-4d72-8ffa-4a76980963a5)

**Comment by mmizalmond** [comment]
This is working correctly, thank you!
