### ISSUE TITLE
🐛 Test/Fix Roundtripping

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/west-virginia-university#104]
## Summary
Roundtripping was part of the previous phase of work for WVU, however it is not fully working. As part of phase 2, WVU would like this fixed. We need to test it to figure out what's wrong. 

[Sample CSV files to test with](https://drive.google.com/drive/u/0/folders/1bHSuGP5Z1RUjo_poMEDXgzBbepEStHXf)

## Accepted Criteria
- [ ] Roundtripping has been tested locally
- [ ] Roundtripping works (reimport the exported csv)

### Related tickets: 
- https://github.com/scientist-softserv/west-virginia-university/issues/9
- https://github.com/scientist-softserv/west-virginia-university/issues/64

### Related PRs: 
- https://github.com/wvulibraries/hydra_acda_portal_public/pull/8
- https://github.com/scientist-softserv/west-virginia-university/pull/83

# Acceptance Criteria

- [ ]  Round trip a records with no changes and it changes nothing in the work.
- [ ]  Round trip a record with changes and it will update the metadata

# Screenshots / Video

<details><summary>When attempting to roundtrip, the system throws a "Error: RuntimeError - ID has already been set to c016_k001_amp3b" error. This means that the system is trying to create another record with the same ID, as opposed to updating that existing record.</summary>

![American Congress Digital Archives Portal 2023-04-14 at 3 40 27 PM](https://user-images.githubusercontent.com/29311858/232166525-77078739-0a8d-4ab9-889f-8039f10f831b.jpg)
![American Congress Digital Archives Portal 2023-04-14 at 3 40 37 PM](https://user-images.githubusercontent.com/29311858/232166532-8009f589-bace-4613-babd-741285a0f606.jpg)
</details>

# Testing Instructions and Sample Files

- [ ] Run WVU on your machine locally
- [ ] Navigate to http://localhost:3000/importers
- [ ] Import this CSV: [DoleSampleMetadata v4e.csv](https://github.com/scientist-softserv/west-virginia-university/files/11237570/DoleSampleMetadata.v4e.csv)
  - If you've imported this same CSV to your local machine, you'll have to make changes to each record's `dcterms:identifier` field to make sure that they are unique from any pre-existing imports. You can simply add a `a` or `b` to the end of each `dcterms:identifier` 
  - `Name`: something remarkable for you to remember
  - `Parser`: CSV
  - `Visibility`: Public
  - Upload a file
  - you can leave the rest of the fields blank
  - Create and import
- [ ] From http://localhost:3000/importers > click into the importer you created > click into an entry show page > click to view the entry's work show page > take a screenshot of the work show page so you can compare the beginning metadata to the roundtripped metadata
- [ ] To test the edge case without any changes to CSV:
  - [ ] Upon completion of the import, navigate to http://localhost:3000/exporters
  - [ ] Create a new exporter:
    - `Name`: something remarkable for you to remember
    - `Type of export`: Metadata only
    - `Export from`: Importer
    - `Importer`: find the importer you made from the 3rd step
    - `Export format`: CSV
    - you can leave the other fields blank
    - Create and export
  - [ ] When the exporter is complete, download the resulting ZIP. Unzip the file to retrieve the CSV.
  - [ ] Create a new importer.
    - `Name`: something remarkable for you to remember
    - `Parser`: CSV
    - `Visibility`: Public
    - Upload the untouched CSV file you unzipped from the downloaded export
    - you can leave the rest of the fields blank 
    - Create and import
  - [ ] Check that your new importer completes without error
  - [ ] Navigate to the same work show page that you screenshotted. Refresh the page. Compare this roundtripped metadata to the pre-round tripped screenshot.
  - [ ] There should be no changes
- [ ] To test the edge case without any changes to CSV:
  - [ ] Complete all of the steps above, but instead:
    - [ ] Instead of leaving the exported CSV without any changes, change the exported CSV's metadata.
      - [ ] Add the word `edit` to one of the record's titles
      - [ ] Remove one of the entry's metadata in a field to test roundtripping deleted metadata
      - [ ] Add metadata into one of the entry's fields that was previously blank to test roundtripping added metadata
    - [ ] When you are checking the roundtripped work show pages pages, confirm that all 3 edits you made are reflected

**Comment by ShanaLMoore** [comment]
# Local Testing: 


Imported Sample CSV: [DoleSampleMetadata v4e.csv](https://github.com/scientist-softserv/west-virginia-university/files/11237570/DoleSampleMetadata.v4e.csv)



![Image](https://github.com/scientist-softserv/west-virginia-university/assets/10081604/7dfe802d-9be9-47df-9ccf-3dfc76495bb9)




Exported imported CSV, METADATA ONLY: 



![Image](https://github.com/scientist-softserv/west-virginia-university/assets/10081604/a7db56a7-3486-44c5-b357-2c5ee62b06cd)




UPDATED the title of one of the works of the exported file. Create a new importer, imported the edited exported work: 



![Image](https://github.com/scientist-softserv/west-virginia-university/assets/10081604/22c84e79-57ca-436c-a4f6-5831ca7aa716)



Edited exported file: [export_1_from_importer_1.csv](https://github.com/scientist-softserv/west-virginia-university/files/13125508/export_1_from_importer_1.csv)


![Image](https://github.com/scientist-softserv/west-virginia-university/assets/10081604/4eef3213-baa3-4698-a0c8-3ac9521e9e4e)



VERIFIED works already created stayed the same. The work with the updated title got updated: 




![Image](https://github.com/scientist-softserv/west-virginia-university/assets/10081604/34ff5534-6c6f-4337-a8b2-1392cc567d71)

It looks like round tripping mostly works. I am seeing quite a few errors on import that I'll look into. @jillpe Could we verify the exact issue the client is noticing when they say it "doesn't work"?  


Errors: 

![Image](https://github.com/scientist-softserv/west-virginia-university/assets/10081604/3451e733-ab35-4855-b93e-5786c2b8d823)

## Additional notes


Metadata export with files does not work. it fails on undefined methods because this application doesn't use [hydra-works](https://github.com/samvera/hydra-works/blob/main/lib/hydra/works/models/concerns/work_behavior.rb) like Hyrax does. 




![Image](https://github.com/scientist-softserv/west-virginia-university/assets/10081604/073cebb8-a3a2-4a33-a034-9ad9655e4fcd)

**Comment by kirkkwang** [comment]
✅ Pass

![Image](https://github.com/scientist-softserv/west-virginia-university/assets/19597776/b5bf744e-e275-452a-9676-5e5a0bf47954)







![Image](https://github.com/scientist-softserv/west-virginia-university/assets/10081604/89607d77-dde7-4688-ab8a-823f3c3b3b84)

**Comment by jmm0177** [comment]
It looks like the roundtripping is working well for the most part, except for changes to the edm:preview field. The metadata is being updated, but the processing of the thumbnails doesn't seem to work. I've tried altering a record in the system with a bad edm:preview thumbnail and to see if it would delete the thumbnail image that had been created previously, but it does not. I also tried importing a new CSV into an empty system with a bad edm:preview link, so a thumbnail image wouldn't be generated, and then tried importing one with a correct edm:preview link, but a thumbnail is not generated. I can see in bulkrax that the metadata is being updated, but something is happening with the processing that it's not being triggered in reimports. Let me know if any of this doesn't make sense.

**Comment by ShanaLMoore** [comment]
@jmm0177 Could you please attach the files you are importing so that we can see the exact examples you're using? and link us to the importers on staging.

**Comment by jmm0177** [comment]
I was testing with these. 
[export_42_from_importer_1a.csv](https://github.com/scientist-softserv/west-virginia-university/files/13253364/export_42_from_importer_1a.csv)
[export_42_from_importer_1b.csv](https://github.com/scientist-softserv/west-virginia-university/files/13253365/export_42_from_importer_1b.csv)
[export_42_from_importer_1c.csv](https://github.com/scientist-softserv/west-virginia-university/files/13253366/export_42_from_importer_1c.csv)
[export_42_from_importer_1.csv](https://github.com/scientist-softserv/west-virginia-university/files/13253368/export_42_from_importer_1.csv)

**Comment by ShanaLMoore** [comment]
Thanks, So am I correctly understanding that the preview/edm:preview points to a url that should pull in a file? And the expectation is that file should be attached to the work/used as a thumbnail? 

@jmm0177

**Comment by jmm0177** [comment]
Here they are: 

[export_42_from_importer_1.csv](https://github.com/scientist-softserv/west-virginia-university/files/13253401/export_42_from_importer_1.csv) This is the original file I downloaded through the exporter.
[export_42_from_importer_1a.csv](https://github.com/scientist-softserv/west-virginia-university/files/13253420/export_42_from_importer_1a.csv) This file is one that has an incorrect edm:preview link for the record with id= ph_035_041_001.
[export_42_from_importer_1b.csv](https://github.com/scientist-softserv/west-virginia-university/files/13253432/export_42_from_importer_1b.csv) This one has a completely wrong URL for edm:preview and edm:isShownAt.

**Comment by jmm0177** [comment]
Oops, and here are the test importers. I was changing around the files, so there may be some inconsistencies between the importers and the files. 
https://congressarchivesdev.lib.wvu.edu/importers/48
https://congressarchivesdev.lib.wvu.edu/importers/49
https://congressarchivesdev.lib.wvu.edu/importers/50
https://congressarchivesdev.lib.wvu.edu/importers/51
https://congressarchivesdev.lib.wvu.edu/importers/52
https://congressarchivesdev.lib.wvu.edu/importers/53

**Comment by jmm0177** [comment]
@ShanaLMoore Yes, that's correct. On an initial import, the system uses the edm:preview link (which goes directly to a file) to get the file and process it into a thumbnail.

**Comment by jmm0177** [comment]
@kirkkwang Roundtripping of metadata is working correctly. A new ticket: https://github.com/scientist-softserv/west-virginia-university/issues/155 has been opened for the thumbnail issue.
