### ISSUE TITLE
Facets are in alphabetical order

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/west-virginia-university#106]
<details>
<summary>Screenshots</summary>

## Before
![Screenshot 2023-10-18 at 6 26 41 PM](https://github.com/wvulibraries/hydra_acda_portal_public/assets/17851674/805e0b86-92e4-4ed7-b817-917a41a798ad)

## After
![Screenshot 2023-10-19 at 10 43 04 AM](https://github.com/scientist-softserv/west-virginia-university/assets/17851674/8b91d810-8ef9-4c74-8eb2-a2d85c815346)

</details>

# Testing

- [ ] Verify that all facts render alphabetically

**Comment by ShanaLMoore** [comment]
# QA Results: Pass ✅ 

- [x]  Verify that all facts render alphabetically


![Image](https://github.com/scientist-softserv/west-virginia-university/assets/10081604/be6b562d-974b-4d60-88eb-7245793fa794)

**Comment by mmizalmond** [comment]
Looks great, thanks!
