### ISSUE TITLE
Put bulkrax behind authentication

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/west-virginia-university#11]
Part of #3 

#Summary

As far as the app is concerned anyone should be able to access and use bulkrax.  BUt we will remove the links to bulkrax from the app and just provide a URL for access. 
Those URLs will be to be protected by WVU to only be accessible from WVU library staff.  This will be accomplished through a combination of NGINIX configuration and IP tables.  
Additionally we will add basic http auth to those pages.  

We are to send over Rob what the URLS are that need protecting, add http basic, and we can send over what we think the NGINX settings should  be.  

# Acceptance Criteria

- [ ] If I have the URL for bulkrax pages I can find bulkrax and can import (no user, or the 1 user the system has can be utilized)
- [ ] Bulkrax pages are behind a basic http auth
  - [ ] auth info is not hard-coded (hide it using an ENV var, etc) 
- [ ] We have sent over URLS 
- [ ] If I'm not signed into the site, I can still access the Bulkrax pages if I get past the basic HTTP auth popup 
  - [Additional details](https://github.com/scientist-softserv/west-virginia-university/issues/11#issuecomment-1478498242) 

# Notes

Bulkrax adds code to the Ability model that assumes the method `can_create_any_work?` exists.

```
    def can_import_works?
      can_create_any_work?  
    end

    def can_export_works?
       can_create_any_work?  
    end
```
This method does not exist in WVU Hydra

### Acceptance Criteria
- [ ] Bulkrax does not throw error for `can_create_any_works?` missing

### Implementation
- using ` if defined?(::Hyrax)` as a wrapper can be a solution. This code will be added directly to Bulkrax
- Add ticket for WVU board to discuss with client how they want to manage the permissions for accessing Bulkrax imports and exporters
- if Hyrax isn't defined, should it be admin?

**Comment by crisr15** [comment]
Asked client about roles in client slack: https://congressarchives.slack.com/archives/C048SB2J287/p1676504543876689

**Comment by crisr15** [comment]
Summary and acceptance criteria updated after meeting on March 7th.

**Comment by crisr15** [comment]
Split into 2 tickets: 

Can improt and export.  

Routes for bulkrax get put under basic auth.

**Comment by bkiahstroud** [comment]
Code for ref in Hyku: https://github.com/samvera/hyku/blob/main/app/controllers/application_controller.rb#L56-L58

**Comment by bkiahstroud** [comment]
Implementation suggestion: https://blog.arkency.com/common-authentication-for-mounted-rack-apps-in-rails/

**Comment by summer-cook** [comment]
Note: once https://github.com/scientist-softserv/west-virginia-university/pull/48 is merged, we will need to add `BULKRAX_USERNAME` & `BULKRAX_PW` env vars to the server
