### ISSUE TITLE
Map the Metadata Properties to a Chicago Citation format

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/west-virginia-university#113]
Metadata mapping for Chicago Citations, which we will use as the default citation for the site.

Information Field

* Title Collection Title (dcterms:title)
* Date Date (dcterms:created)
* Collection # isPartof (dcterms:isPartOf)
* Box # isPartof (dcterms:isPartOf)
* Folder # isPartof (dcterms:isPartOf)
* Collection title Relation (dcterms:relation)
* Repository Contributing Institution (dcterms:provenance)
* Location of Contributing Institution (dcterms:provenance)
* Repository
* URL (URL of item)

The terms are described in the model via properties.

Examples of Citation Builders are available at https://github.com/scientist-softserv/palni-palci/blob/dfe9ecdc5c0b5de2605ecbf90a2ffdb600a4fb3f/app/helpers/hyrax/citations_behaviors/formatters.rb#L4-L30

Note: That builder is likely overkill and we could consider a plain old ruby object for generating the citation.  Think of this is a presenter; it could generate the inner HTML of a Chicago Style citation.

Jill confirmed the client will not be requesting other citation styles in the future, so the need for it to be dynamic may not be required. 

## Testing Instructions

- [ ] Navigate to a work
- [ ] Observe that the citation is correct

## Notes

Title or description of item, date (day, month, year), Collection number or identifier, box number, folder number, Collection Name, Name of Repository, Location of Repository. URL if applicable.
Mapped, that would look like: dcterms:title, dcterms:created, dcterms:ispartof, dcterms:relation, dcterms:provenance. URL of item.

**Comment by ShanaLMoore** [comment]
gems to consider: 
- https://rubygems.org/gems/citeproc-ruby/versions/2.0.0?locale=en
- https://rubygems.org/gems/csl-styles/versions/1.0.1.11

cc @laritakr for notre dame implementation

**Comment by jillpe** [comment]
Structure/mappings confirmed by client:

Title or description of item, - `dcterms:title`
date (day, month, year), - `dcterms:created`
Collection number or identifier, - `dcterms:ispartof`
 box number, , - `dcterms:relation`
folder number - `dcterms:provenance`
Collection Name, - `dcterms:relation`
Name of Repository, - `dcterms:provenance`
Location of Repository. - `dcterms:provenance`
URL if applicable. - URL

**Comment by ShanaLMoore** [comment]
# QA Results: Pass ✅ 

- [X] a work renders a CSL Citation

![Image](https://github.com/scientist-softserv/west-virginia-university/assets/10081604/c1398d2f-0bdc-4ade-bd75-b853b232c97f)

**Comment by mmizalmond** [comment]
We're _almost_ there, but not quite. 

- [x] 1. the citation still seems to be pulling from the dcterms:creator field (see above), which we can get rid of. No name is necessary. 
- [x] 2. title is correctly mapped to dcterms:title field
- [x] 3. date is correctly mapped to dcterms:created field
- [x] 4. Collection/Box/Folder information seems to be truncated, only showing part of the dcterms:ispartof field instead the entire contents (see attached screengrab, it's only saying 'Folder 56' but the field reads MANUSCRIPT-HCPC00011, Speeches, Box SP7, Folder 56 in physical location metadata to left)
- [x] 5. there should be a comma after each field up until dcterms:provenance, not a period. 
- [x] 6. period after dcterms:provenance field is correct 
- [x] 7. period after url is correct 

![Image](https://github.com/scientist-softserv/west-virginia-university/assets/148279275/e2314415-f52e-4535-9cd0-65974cfb7002)

**Comment by ShanaLMoore** [comment]
@mmizalmond We've made the requested changes: 

![Screenshot 2023-10-27 at 13-31-16 Social Security Rescued Press Release and Newsletter - American Congress Digital Archives Portal](https://github.com/scientist-softserv/west-virginia-university/assets/10081604/4b2604ae-80ce-490d-a24d-e1586481c898)

**Comment by ShanaLMoore** [comment]
# QA RESULTS [REWORK]: Pass ✅ 
- [x]     1. the citation still seems to be pulling from the dcterms:creator field (see above), which we can get rid of. No name is necessary.
- [x]     2. title is correctly mapped to dcterms:title field
- [x]     3. date is correctly mapped to dcterms:created field
- [x]     4. Collection/Box/Folder information seems to be truncated, only showing part of the dcterms:ispartof field instead the entire contents (see attached screengrab, it's only saying 'Folder 56' but the field reads MANUSCRIPT-HCPC00011, Speeches, Box SP7, Folder 56 in physical location metadata to left)
- [x]     5. there should be a comma after each field up until dcterms:provenance, not a period.
- [x]     6. period after dcterms:provenance field is correct
- [x]     7. period after url is correct


![Image](https://github.com/scientist-softserv/west-virginia-university/assets/10081604/3a721148-9707-4a47-b1da-f3384cfe715a)

**Comment by kirkkwang** [comment]
# QA PASSED ✅



![Image](https://github.com/scientist-softserv/west-virginia-university/assets/19597776/21c53b1d-7812-4066-9d24-47a1da45335f)

**Comment by mmizalmond** [comment]
Looks good!
