### ISSUE TITLE
Render the Chicago Citation format on the Show page of an item

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/west-virginia-university#114]
They would like  chicago citation and the following note to render on the show page of an item

'Note: These citations are programmatically generated and may be incomplete.'

[Example from pals (click citation button)](https://bloomsburg.commons-archive.org/concern/images/7d293477-5dfb-436d-9d7f-4acf14b64d83):: 

![Image](https://github.com/scientist-softserv/west-virginia-university/assets/10081604/095ffb55-67e1-4ab1-b474-076a6e8f1892)

Depends on:

- #113 

# Testing Instructions

- [ ] Navigate to a work
- [ ] Observe that the citation is correct

**Comment by ShanaLMoore** [comment]
# QA Results: Pass ✅ 

- [X] a work renders a CSL Citation


![Image](https://github.com/scientist-softserv/west-virginia-university/assets/10081604/c1398d2f-0bdc-4ade-bd75-b853b232c97f)

**Comment by mmizalmond** [comment]
This is showing up correctly, thank you.

**Comment by mmizalmond** [comment]
So, in looking at this today, it appears that the dcterms:relation field isn't showing up in the mapping. 

![Image](https://github.com/scientist-softserv/west-virginia-university/assets/148279275/baa5bd25-944b-4a72-bb25-840934b7512e)

In the mapping provided, dcterms:relation should be showing up between dcterms:isPartof and dcterms:provenance. What I should be seeing on screen is: 

_1960's Vietnam era youth's disenchantment w/America_,
approximately 1960's, MANUSCRIPT-HCPC00011, Speeches
Undated, Box SP1, Folder 1, **Senator Daniel K. Inouye Papers**, Hawaii Congressional Papers
Collection, University of Hawai'i at Manoa Library, Honolulu, HI.
https://congressarchivesdev.lib.wvu.edu/cataloq/10524_71360
(accessed November 01, 2023).

**Comment by kirkkwang** [comment]
# QA PASSED ✅



![Image](https://github.com/scientist-softserv/west-virginia-university/assets/19597776/21c53b1d-7812-4066-9d24-47a1da45335f)
