### ISSUE TITLE
Controlled Vocabularies for Advanced Search

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/west-virginia-university#133]
## Summary
WVU would like controlled vocabularies for the `Congress`, `Policy Area`, and `Rights` fields. See doc for vocabularies

[ACDAP_ControlledVocabFields.docx](https://github.com/scientist-softserv/west-virginia-university/files/13168405/ACDAP_ControlledVocabFields.docx)

## Accepted Criteria
- [ ] Controlled vocabularies are implemented for the `Congress` field
- [ ] Controlled vocabularies are implemented for the `Policy Area` field
- [ ] Controlled vocabularies are implemented for the `Rights` field

## Testing Instructions
- [ ] Note that some of the fields have dropdowns
- [ ] Observe that the dropdown options are the ones that are expected

## NOTES
https://github.com/samvera/questioning_authority/wiki/Creating-a-custom-controlled-vocabulary-via-YAML

**Comment by kirkkwang** [comment]
✅ pass

![Image](https://github.com/scientist-softserv/west-virginia-university/assets/19597776/c479854c-6260-4fe2-bcb8-f98bc82a8fa1)

**Comment by mmizalmond** [comment]
These are correct, thank you!
