### ISSUE TITLE
Bulkrax delimiter

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/west-virginia-university#134]
## Summary
WVU would like to be able to input multiple values for the following Bulkrax fields upon import: 

dcterms:date
~dcterms:created~
dcterms:temporal

_Edit: requested the following two and removal of created above on 11/26/2023_
dcterms:creator
dcterms:spatial

They would like to use `;` as the delimiter

## Accepted Criteria
- [ ] dcterms:date can use a `;` as a delimiter for importing multiple values
- [ ] ~dcterms:created can use a `;` as a delimiter for importing multiple values~
- [ ] dcterms:temporal can use a `;` as a delimiter for importing multiple values
- [ ] **dcterms:creator** can use a `;` as a delimiter for importing multiple values
- [ ] **dcterms:spatial** can use a `;` as a delimiter for importing multiple values

## Testing Instructions
- [ ] Initiate a Bulkrax import from the `/importers` route
- [ ] Observe that the values are being split as expected

**Comment by kirkkwang** [comment]
Date is splitting as expected

![Image](https://github.com/scientist-softserv/west-virginia-university/assets/19597776/34d41944-1fd1-4392-9540-6bd95c774012)

**Comment by mmizalmond** [comment]
Delimited fields worked as requested. 

![Image](https://github.com/scientist-softserv/west-virginia-university/assets/148279275/abdacdc5-5aa2-40fa-8491-15ef128179d4)
