### ISSUE TITLE
WVU - autodeploy and fedora instructions.

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/west-virginia-university#2]
# Summary

We want to make deploying WVU easier.  Set up a script that will check for new releases, and if it finds one it will deploy the app.  

Additionally, we need to pull in the changes that set Fedora to be backed by postgres. What steps do they need to take to get this deployed? 

We will need to work with the client to get this installed on the server.  

# Acceptance Criteria

- [ ] Auto deployment setup
- [ ] Production Fedora instructions and code change

# Testing Instructions

Not end user testable.  
Developers: Confirm that when a release is cut a deploy happens.

**Comment by crisr15** [comment]
we need to write a script
that checks github for a new release
and if a new release exists deploy it
we will be using release tags
Check every 5 mins

NNP and DOT had similar setups.

**Comment by crisr15** [comment]
https://github.com/samvera/hyku/blob/main/docker-compose.production.yml#L86-L99
hyku/docker-compose.production.yml at main · samvera/hyku
Hyku: A multi-tenant Hyrax application built on the latest and greatest Samvera community components. Brought to you by the Hydra-in-a-Box project partners and IMLS; maintained by the Hyku Interest...

**Comment by bkiahstroud** [comment]
>Fedora - go to current docker compose yaml and pull in changes. Part about Fedora only.

Get fedora info from Hyku prod docker compose file and update base WVU dc file

**Comment by bkiahstroud** [comment]
Will need to coordinate with the client to get this installed on the server. To test, we will do a release and see if it pulls / updates properly

**Comment by kirkkwang** [comment]
Closed, not part of phase 2 work
