### ISSUE TITLE
Create File upload service - Save File object to Fedora

### ISSUE THREAD

**Issue by sephirothkod** [scientist-softserv/west-virginia-university#27]
We will need to create a class that will create AcdaFile and create the relationship to the Acda work.
- [ ] Create the class (FileFactory or FileUploadService)
- [ ] Save the object to Fedora (Need to figure out the best way to do this)
- [ ] What information needs to be included on the CSV file?
- [ ] Where should the file be located?

**Comment by crisr15** [comment]
Split this into two tickets.  
1) save file object to Fedora.  - 5 points
2) associate file object to work.  - detect type of file and add to the correct field on their object. (audio, video, pdf).  - 2 points.

**Comment by crisr15** [comment]
No longer necessary.  WVU wants the files to link out to their current locations by URL.  Do not ingest files.
