### ISSUE TITLE
Spike - Figure out how to Install Bulkrax

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/west-virginia-university#3]
# Summary

WVU is a hydra app.  They want to use bulkrax to import items.  We need to install bulkrax into the app and work through the installation process to get it working with a hyra app.  

# Acceptance Criteria

- [x] bulkrax has been installed
- [x] you can access the importer page
- [x] hyrax includes and specific code has been worked around.  

# Testing Instructions
(Fill in once we know how bulkrax will work in hydra). 

# Notes
This will be to get Bulkrax importers index and new/edit pages and show pages rendering with no Hyrax errors and appropriate fields to start an importer

There will be sub-tickets for this issue

**Comment by labradford** [comment]
WVU Bulkrax issues

Importers Controller - 
- [ ] Hyrax is not defined 
	# require_dependency 'bulkrax/application_controller'
	# include Hyrax::ThemedLayoutController
- [ ] with_themed_layout not defined
	# with_themed_layout 'dashboard'
- [ ] add_breadcrumb is not defined - commented out all breadcrumb refs

App/views/importer/index.html.erb
- [ ] Header not showing up / no new import button

App/views/importer/new.html.erb
- [x] Simple form not defined (added gem, bundled, ran generator)

App/helpers/bulkrax/importers_helper.rb
- [ ] uninitialized constant Bulkrax::ImportersHelper::Hyrax - available_admin_sets - does Hydra use admin sets?

app/views/bulkrax/importers/_csv_fields.html.erb
- [ ] ActionView::Template::Error (uninitialized constant ActionView::CompiledTemplates::Hyrax) - does Hydra use rights_statements

    - [x] Removed all but CSV parser from Bulkrax initializer
    - [x] Commented out the rights statement
    - [x] Commented out browse everything
    - [x] Gave custom partial to render _wv_csv_fields.html.erb

New importer form
- [ ] Required form field for admin set
- [ ] Parser fields JS not working, don’t get the parser specific form

**Comment by labradford** [comment]
## Exporters

**Comment by labradford** [comment]
## Other Issues
- [ ] CSS not loading
- [ ] JS not loading

**Comment by labradford** [comment]
Spike completed and other tickets are created
