### ISSUE TITLE
Create method in ObjectFactory

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/west-virginia-university#35]
Inside of the ObjectFactory, we need to add a `create` method:

This method will perform the tasks to create an `acda` object (work) without using the Hyrax actor stack.

### Acceptance criteria
- [ ] The create method is added to the `object_factory`
- [ ] the create method will perform the necessary tasks to create an `acda` object

**Comment by crisr15** [comment]
Look at what is happening in the controller and mimic.
