### ISSUE TITLE
Add a method to call create_file service in the ObjectFactory

### ISSUE THREAD

**Issue by labradford** [scientist-softserv/west-virginia-university#37]
Part of #26 
#27 needs to be completed

After the create file upload service is completed, we need a method in the ObjectFactory to call the service.

### Acceptance Criteria
- [ ] a method is added to the ObjectFactory that calls the file upload service
- [ ] when the method is called, an `acda_file` is created 
- [ ] when the method is called, a relationship is created between the `acda` object and the `acda_file` object

**Comment by crisr15** [comment]
No longer necessary. WVU wants the files to link out to their current locations by URL. Do not ingest files.
