### ISSUE TITLE
Fork Repo and Spin up Application Locally

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/west-virginia-university#4]
# Summary

Client Repo is at https://github.com/wvulibraries/hydra_acda_portal_public

# Acceptance Criteria

- [x] Repo exist for softserv
- [x] developers can spin up the application locally

# Notes
Docker file exists but we need to know if we can spin this up locally.

**Comment by labradford** [comment]
- [ ] `docker-compose.dev.yml` file, remove the references to ` - /mnt:/mnt  ` on lines 15 and 129
- [ ] create `env.prod.db` file
- [ ] create `env.prod.hydra` file
- [ ] to start the app `docker compose -f  docker-compose.dev.yml up`
- [ ] once the app is running, bash into web container `docker compose exec web bash`
- [ ] create the db `bundle exec rake db:create`
- [ ] run db migrations `bundle exec rake db:migrate`
- [ ] create a user in the Rails console `bundle exec rails c` `u = User.new(email:<emal>, password:<password>)` `u.save`
- [ ] view the app at `localhost:3000`
