### ISSUE TITLE
Create File Upload Service - Associate file object to work

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/west-virginia-university#44]
# Summary

detect type of file and add to the correct field on their object. (audio, video, pdf). 

# From previous copied ticket.  Update which parts are done previously and which ones are part of this work. 
We will need to create a class that will create AcdaFile and create the relationship to the Acda work.

- [ ] Associate the file with the Acda item (Need to figure out the best way to do this) (New ticket with association)
- [ ] File needs to be associated to the right field in the Acda item (Need to figure out the best way to do this) (New ticket with association)

**Comment by orangewolf** [comment]
need to discuss this after WVU meeting
