### ISSUE TITLE
Add semicolon delimiter to 'Names', 'Policy Area', 'Record Type', and 'Topic'

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/west-virginia-university#73]
# Summary

When testing Dole imports the Names field was bringing in all of the names as one line instead of splitting them into more than one option.  The client would like to use a semicolon as a delimiter for bulkrax on the following fields: Name, Policy Area, Record Type, Topic. 

# Acceptance Criteria

When importing, any items separated by a ';' in the following fields will import as separate field items: 

- [ ] Names
- [ ] Policy Area
- [ ] Record Type
- [ ] Topic

# Notes

Client controls staging.  Test locally and then push code to client.

**Comment by summer-cook** [comment]
Do we need the delimiter to ONLY apply to these 4 fields? Or can it apply to all multi-value fields?
[I believe there is already functionality to add a delimiter](https://github.com/samvera-labs/bulkrax/blob/e6f2cf94730ea7db236a6f3280d3dc3967f5495e/lib/bulkrax.rb#L248), but by default i think it applies to all fields.

**Comment by crisr15** [comment]
This can apply to all multi-value fields
