### ISSUE TITLE
Group of search results metadata can be exported to CSV

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/west-virginia-university#93]
## Summary
related to 
- #90  

WVU would like there users to be able to export metadata for a group of search results via the UI to CSV.

## Acceptance Criteria
- [ ] As a user, I can export metadata for a group of search results via the UI to CSV

## Testing Instructions
- [ ] Initiate a search
- [ ] Click the Export dropdown and export XML
- [ ] Observe the XML is in the desired structure

## Notes
https://github.com/ndlib/curate_nd/pull/955/files

**Comment by ShanaLMoore** [comment]
GBH - implementation: https://github.com/WGBH-MLA/ams/commit/ac0c9d3d15fc6d3a754a07e62be14f9b8cd44939

**Comment by kirkkwang** [comment]
✅ pass, csv was exported


[search-results-2023-10-27_17_00_40.csv](https://github.com/scientist-softserv/west-virginia-university/files/13191451/search-results-2023-10-27_17_00_40.csv)

**Comment by mmizalmond** [comment]
Same problem as ticket #93. Identifier in export also has site url. Can we remove http://congressarchivesdev.liblwvu.edu/record/ from identifier in the export? 

![Image](https://github.com/scientist-softserv/west-virginia-university/assets/148279275/9783edb4-4c68-4b07-8c21-d43208baadd8)

**Comment by ShanaLMoore** [comment]
❌ 

Can we remove http://congressarchivesdev.liblwvu.edu/record/ from identifier in the export?

[search-results-2023-10-30_20 07 27.csv](https://github.com/scientist-softserv/west-virginia-university/files/13209588/search-results-2023-10-30_20.07.27.csv)


<img width="408" alt="image" src="https://github.com/scientist-softserv/west-virginia-university/assets/10081604/6dd09e0a-c5cf-44d1-a649-fbb30e3b4bc1">

**Comment by kirkkwang** [comment]
a fix will make it look like this
<img width="325" alt="image" src="https://github.com/scientist-softserv/west-virginia-university/assets/19597776/8cb5da7e-0a46-47ea-a89e-6379f86f60cd">

**Comment by kirkkwang** [comment]
# QA RESULTS PASS ✅

<img width="404" alt="image" src="https://github.com/scientist-softserv/west-virginia-university/assets/19597776/a3018ead-d45b-45cc-b8d9-289b6253f9bf">

Identifiers do not have the Congress Archives URL prepended

**Comment by mmizalmond** [comment]
Looks good! We appear to have resolved this issue.
