### ISSUE TITLE
Export button with capability to select format you want (CSV or XML)

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/west-virginia-university#95]
## Summary
related to 
- #90 

WVU would like their users to be able to export metadata for a group of search results via the UI to CSV and XML (if budget allows). One option is a button at the top of the search result page, “Export All Search Results.”, but this will be determined in the next meeting.

![Image](https://github.com/scientist-softserv/west-virginia-university/assets/84697174/5a97a0ee-5262-4616-adc4-92c18c9162f8)

## Acceptance Criteria
- [ ] As a user, I can click a button through the UI that will export the metadata of a group of search results to CSV or XML (if budget allows)

## Testing Instructions

**Comment by jillpe** [comment]
Depends on if XML will be covered in this phase of work

**Comment by ShanaLMoore** [comment]
GBH:

![Image](https://github.com/scientist-softserv/west-virginia-university/assets/10081604/01088b7f-889e-4a95-b580-ff6c5a5bad81)

**Comment by ShanaLMoore** [comment]
Closing, this will be completed and tested as part of #94
