### ISSUE TITLE
As a user I can use quotations marks in my search to receive results that have that exact phrase in the exact order it was entered

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/west-virginia-university#97]
## Acceptance Criteria
- [x] As a user I can use quotations marks in my search to receive results that have that exact phrase in the exact order it was entered
- [x] Make all fields search work

## Testing Instructions

- [ ] Initiate a search and observe the number of results
- [ ] Initiate another search of something more precise with quotations
- [ ] Observe that the number should be smaller

**Comment by kirkkwang** [comment]
# QA Results: Pass ✅ 


I believe this is currently working, i did a title search for `Senator Dole` and got this:

![image](https://github.com/scientist-softserv/west-virginia-university/assets/19597776/fdfd20f8-0870-4510-8a11-66b645981991)

Then I searched for `"Senator Dole"` and got this:

![image](https://github.com/scientist-softserv/west-virginia-university/assets/19597776/aa816675-2907-4e38-af51-bf97751bd4eb)

The second search has one less result.

**Comment by mmizalmond** [comment]
This is working correctly. Thank you!
