### ISSUE TITLE
As a user, I can use the advanced search functionality and receive results through the regular search

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/west-virginia-university#99]
## Summary
related to 
- #92 

## Accepted Criteria
- [ ] As a user, I can use the advanced search functionality and receive results through the regular search

## Testing Instructions
- [ ] Observe that the fields are in the desired order
- [ ] Observe that the "Additional fields" button works
- [ ] In the advanced search, do a search and observe it takes you to the catalog page

**Comment by jillpe** [comment]
The following is the confirmed preferences for advanced search. Can we double check that what we implemented matches this?


I have more information regarding our preferences for the advanced search. We like the look of https://bloomsburg.commons-archive.org/advanced and would like to replicate that.
1. Search tips stay the same.

2. Match “all” as the default setting

3. Fields are  a. Keyword  b. Creator
  c. Date
  d. Names
  e. Title

4. User can click “additional fields” button to reveal:
  a. Collection Title
  b. Congress
  c. Contributing Institution
  d. Description
  e. Identifier
  f. Language
  g. Location Represented
  h. Policy Area
  i. Publisher
  j. Record Type
  k. Rights
  l. Topic

5. The following fields will have controlled vocabularies with dropdown menus (like “Type or Resource Type” field on Bloomsburg Commons)
  a. Congress
  b. Policy Area
  c. Rights

I think that’s it. I will send along the controlled vocabularies for the three metadata fields mentioned separately.

**Comment by kirkkwang** [comment]
✅ pass


![Image](https://github.com/scientist-softserv/west-virginia-university/assets/19597776/e6b18d86-b19b-4f29-a5ff-cef53b35e35a)

**Comment by mmizalmond** [comment]
Keyword field is missing from first five fields on advanced search. 

![Image](https://github.com/scientist-softserv/west-virginia-university/assets/148279275/b1c31142-789a-42ac-89aa-1357d0a7432f)
